# Generated by Django 3.1.5 on 2021-01-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('hash', models.TextField()),
                ('time', models.DateTimeField()),
                ('miner', models.TextField()),
                ('transactions', models.IntegerField()),
            ],
        ),
    ]
